chore: update to new multiformats
libp2p/js-libp2p-delegated-content-routing pull request #52
Opened 2021-06-02 13:36 UTC by achingbrain

Depends on:

- [ ] https://github.com/multiformats/js-multiformats/pull/91

BREAKING CHANGE: uses the CID class from the new multiformats module

2021-07-06 19:52 UTC, vasco-santos approved these changes
LGTM

2021-07-06 19:55 UTC, vasco-santos requested changes
Can you update the Readme to have ipfsHttpClient use the factory?

2021-07-06 20:00 UTC, achingbrain commented
Done

2021-07-07 06:31 UTC, vasco-santos approved these changes

2021-07-07 06:31 UTC, merged